### Course List
GET http://localhost:8080/course/list


### Course Create
POST http://localhost:8080/course/create
Content-Type: application/json

{
  "name": "1C",
  "prise": 100,
  "duration": 6.0
}

### Course Create List
POST http://localhost:8080/course/create
Content-Type: application/json

//{
//  "name": "HTML",
//  "prise": 300,
//  "duration": 3.0
//}
//{
//  "name": "CSS",
//  "prise": 200,
//  "duration": 2.0
//}
{
  "name": "Pyton",
  "prise": 800,
  "duration": 8.5
}

### Course Update
PUT http://localhost:8080/course/update/1
Content-Type: application/json

{
  "name": "Java",
  "prise": 900,
  "duration": 9.0
}


### Course Get Id
GET http://localhost:8080/course/get/2

### Course Delete
DELETE http://localhost:8080/course/delete/1

### Course GetByName
GET http://localhost:8080/course/getByName/Java

### Course GetByPrise
GET http://localhost:8080/course/getByPrise/100.0

### Course GetByDuration
GET http://localhost:8080/course/getByDuration/9

### Course GetByBetweenPrise
GET http://localhost:8080/course/getByBeetwenPrise?beginPrise=100&endPrise=1000

### Course GetByBeetwenDate
GET http://localhost:8080/course/getByBeetwenDate?beginDate=2023-04-06&endDate=2023-04-08