### Course List
GET http://localhost:8080/course/list


### Course Create
POST http://localhost:8080/course/create
Content-Type: application/json

{
  "name": "1C",
  "price": 100,
  "duration": 6.0
}

### Course Create List
POST http://localhost:8080/course/create
Content-Type: application/json

[
  {
    "name": "C#",
    "price": 500,
    "duration": 9.0
  },
  {
    "name": "HTML",
    "price": 300,
    "duration": 2.0
  },
  {
    "name": "CSS",
    "price": 200,
    "duration": 1.0
  }
]

### Course Update
PUT http://localhost:8080/course/update/1
Content-Type: application/json

{
  "name": "Java",
  "price": 900,
  "duration": 9.0
}


### Course Get Id
GET http://localhost:8080/course/get/1

### Course Delete
DELETE http://localhost:8080/course/delete/1