### StudentCourse List
GET http://localhost:8080/studentcourse/list


### StudentCourse Create
POST http://localhost:8080/studentcourse/create
Content-Type: application/json

{
  "student": {
    "id": 1,
    "name": "Vali",
    "surName": "Valiev",
    "level": 1,
    "age": 18,
    "gender": "MAN",
    "createdDate": "2023-04-05T15:21:17.5795324"
  },
  "course":  {
    "id": 1,
    "name": "1C",
    "price": 100.0,
    "duration": 6,
    "createdDate": "2023-04-05T15:21:06.342104"
  },
  "mark": 5
}


### StudentCourse Create List
POST http://localhost:8080/studentBook/create/allStudentBook
Content-Type: application/json

[
  {
    "student": {
      "name": "Toshmat",
      "surName": "Toshmatov",
      "phone": "3",
      "createdDate": "2002-11-05"
    },
    "book": {
      "title": "JavaScript",
      "author": "Eshmat",
      "publishYear": "2005-06-03"
    },
    "createdDate": "2023-03-20",
    "returnedDate": "2023-03-30",
    "duration": "10 days"
  },
  {
    "student": {
      "name": "Jabbor",
      "surName": "Jabborov",
      "phone": "4",
      "createdDate": "1999-09-15"
    },
    "book": {
      "title": "C++",
      "author": "Toshmat",
      "publishYear": "2012-11-11"
    },
    "createdDate": "2023-03-01",
    "returnedDate": "2023-03-15",
    "duration": "15 days"
  }
]

### StudentCourse Update
PUT http://localhost:8080/studentcourse/update/
Content-Type: application/json

{
  "student": {
    "name": "Rashid",
    "surName": "Rashidov",
    "phone": "5",
    "createdDate": "1999-12-11"
  },
  "book": {
    "title": "Go",
    "author": "Clarc",
    "publishYear": "2015-06-14"
  },
  "createdDate": "2023-03-10",
  "returnedDate": "2023-03-22",
  "duration": "12 days"
}


### StudentCourse Get Id
GET http://localhost:8080/studentcourse/get/1

### StudentCourse Delete
DELETE http://localhost:8080/studentcourse/delete/