### Student List
GET http://localhost:8080/student/list


### Student Create
POST http://localhost:8080/student/create
Content-Type: application/json

{
  "name": "Vali",
  "surName": "Valiev",
  "level": 1,
  "age": 18,
  "gender": "MAN"
}

### Student Create List
POST http://localhost:8080/student/create/allStudent
Content-Type: application/json

[
  {
    "name": "Eshmat",
    "surName": "Eshmatov",
    "phone": "2",
    "createdDate": "2000-01-03"
  },
  {
    "name": "Toshmat",
    "surName": "Toshmatov",
    "phone": "3",
    "createdDate": "2002-11-05"
  },
  {
    "name": "Jabbor",
    "surName": "Jabborov",
    "phone": "4",
    "createdDate": "1999-09-15"
  }
]

### Student Update
PUT http://localhost:8080/student/update/1
Content-Type: application/json

{
  "name": "Ali",
  "surName": "Aliyev",
  "level": 2,
  "age": 19,
  "gender": "MAN"
}


### Student Get Id
GET http://localhost:8080/student/get/1

### Student Delete
DELETE http://localhost:8080/student/delete/1