### Student List
GET http://localhost:8080/student/list


### Student Create
POST http://localhost:8080/student/create
Content-Type: application/json

{
  "name": "Vali",
  "surName": "Valiev",
  "level": 1,
  "age": 18,
  "gender": "MAN"
}

### Student Create List
POST http://localhost:8080/student/create
Content-Type: application/json

//{
//  "name": "Natasha",
//  "surName": "Bereznova",
//  "level": 5,
//  "age": 22,
//  "gender": "WOMAN"
//}
//{
//  "name": "Eshmat",
//  "surName": "Eshmatov",
//  "level": 4,
//  "age": 22,
//  "gender": "MAN"
//}
{
  "name": "Aliya",
  "surName": "Aliyaeva",
  "level": 3,
  "age": 19,
  "gender": "WOMAN"
}

### Student Update
PUT http://localhost:8080/student/update/1
Content-Type: application/json

{
  "name": "Ali",
  "surName": "Aliyev",
  "level": 2,
  "age": 19,
  "gender": "MAN"
}


### Student Get Id
GET http://localhost:8080/student/get/

### Student Delete
DELETE http://localhost:8080/student/delete/

### Student GetByName
GET http://localhost:8080/student/getByName/Ali

### Student GetBySurName
GET http://localhost:8080/student/getBySurName/Aliyev

### Student GetByLevel
GET http://localhost:8080/student/getByLevel/2

### Student GetByAge
GET http://localhost:8080/student/getByAge/19

### Student GetByGender
GET http://localhost:8080/student/getByGender/WOMAN

### Student getByDate
GET http://localhost:8080/student/getByDate/2023-04-06

### Student GetByBeetwenDate
GET http://localhost:8080/student/getByBeetwenDate?beginDate=2023-04-06&endDay=2023-04-08